apiVersion: v1
kind: Service
metadata:
  name: user_service
spec:
  selector:
    pod: users-service-pod # Трафик будет перенаправляться к подам с этой меткой.
  ports:
    - port: 8080 # Порт, куда будет перенаправляться трафик
  type: NodePort