apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus-microservice'
        static_configs:
          - targets: ['microservice:8081']
      - job_name: 'prometheus-userservice'
        static_configs:
          - targets: ['user_service:8080']
      - job_name: 'prometheus-gateway'
        static_configs:
          - targets: ['gateway:8083']

