apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    pod: prometheus-pod # Трафик будет перенаправляться к подам с этой меткой.
  ports:
    - port: 9090 # Порт, куда будет перенаправляться трафик
  type: NodePort