// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProgramInput struct {
	Name          string `json:"name"`
	Description   string `json:"description"`
	Price         int32  `json:"price"`
	Confirmuserid string `json:"confirmuserid"`
}

type Mutation struct {
}

type Program struct {
	Confirmedby  string `json:"confirmedby"`
	Description  string `json:"description"`
	Name         string `json:"name"`
	Price        int32  `json:"price"`
	Wasconfirmed string `json:"wasconfirmed"`
}

type ProgramFilterInput struct {
	Confirmedby  *string `json:"confirmedby,omitempty"`
	Description  *string `json:"description,omitempty"`
	Name         *string `json:"name,omitempty"`
	Price        *int32  `json:"price,omitempty"`
	Wasconfirmed *string `json:"wasconfirmed,omitempty"`
}

type Query struct {
}

type UpdateProgramInput struct {
	ID          string `json:"id"`
	Name        *int32 `json:"name,omitempty"`
	Description *int32 `json:"description,omitempty"`
	Price       *int32 `json:"price,omitempty"`
}
