apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    pod: grafana-pod # Трафик будет перенаправляться к подам с этой меткой.
  ports:
    - port: 3000 # Порт, куда будет перенаправляться трафик
      nodePort: 3000 # Порт, доступный из вне кластера.
  type: NodePort