apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: grafana-pod
  template:
    metadata:
      labels:
        pod: grafana-pod
    spec:
      containers:
      - name: grafana-container
        image: docker.io/grafana/grafana-oss:latest
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "admin"
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: grafana-provisioning
            mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
            subPath: datasource.yaml
            readOnly: true
          - name: grafana-dashboard-provider
            mountPath: /etc/grafana/provisioning/dashboards/dashboard-provider.yaml
            subPath: dashboard-provider.yaml
            readOnly: true
          - name: grafana-dashboards
            mountPath: /var/lib/grafana/dashboards
            readOnly: true
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pv-claim
        - name: grafana-provisioning
          configMap:
            name: grafana-datasource
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
