apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: gateway-pod
  template:
    metadata:
      labels:
        pod: gateway-pod
    spec:
      containers:
      - name: gateway-container
        image: konst26/gateway:5
        env:
          - name: MICROSERVICE_URL
            value: "http://microservice:8081"
          - name: USER_SERVICE_URL
            value: "http://user-service:8080"
        readinessProbe:
          httpGet:
            path: /health
            scheme: HTTP
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1