apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Чтобы данные сохранились после удаления PVC.
  hostPath:
    path: /mnt/data/kafka # Путь на ноде, где будут лежать данные.
  claimRef:
    namespace: default
    name: kafka-pv-claim
