apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Чтобы данные сохранились после удаления PVC.
  hostPath:
    path: /mnt/data/redis # Путь на ноде, где будут лежать данные.
  claimRef:
    namespace: default
    name: redis-pv-claim
