// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/gateway/programs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список программ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Получить все программы тренировок",
                "responses": {
                    "200": {
                        "description": "Успешно получены все программы тренировок",
                        "schema": {
                            "$ref": "#/definitions/main.Program"
                        }
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "421": {
                        "description": "Не удалось перенаправить запрос",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет все программы тренировок из списка",
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Удалить все программы тренировок",
                "responses": {
                    "200": {
                        "description": "Успешно удалены"
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/gateway/programs/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает программу тренировок по индексу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Получить программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор программы",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно получена программа тренировок",
                        "schema": {
                            "$ref": "#/definitions/main.Program"
                        }
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с указанным идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет в список тренировок новую программу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Добавить новую программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название программы",
                        "name": "Name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание программы",
                        "name": "Description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Стоимость программы",
                        "name": "Price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id подтверждающего пользователя",
                        "name": "ConfirmUserId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно добавлена"
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет программу тренировок из списка",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Удалить программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор удаляемой программы",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно удалена"
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с указанным идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает программу тренировок по индексу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Обновить программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор обновляемой программы",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название программы",
                        "name": "Name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Описание программы",
                        "name": "Description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Стоимость программы",
                        "name": "Price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно обновлена"
                    },
                    "400": {
                        "description": "Неверное значение цены",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с таким идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/gateway/programs/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает кол-во документов",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Получить кол-во программ",
                "responses": {
                    "200": {
                        "description": "Кол-во элементов",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "401": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/gateway/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список пользователей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Получить всех пользователей",
                "responses": {
                    "200": {
                        "description": "Успешно получены все пользователи",
                        "schema": {
                            "$ref": "#/definitions/main.User"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет всех пользователей из списка",
                "tags": [
                    "Пользователи"
                ],
                "summary": "Удалить всех пользователей",
                "responses": {
                    "200": {
                        "description": "Успешно удален"
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/gateway/users/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает пользователя по индексу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Получить пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно получен пользователь",
                        "schema": {
                            "$ref": "#/definitions/main.User"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с указанным идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет пользователя от имени авторизованного пользователя. Для публичной регистрации используйте /register.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Добавить нового пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя",
                        "name": "Name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Фамилия",
                        "name": "Surname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Логин",
                        "name": "login",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Возвраст",
                        "name": "Age",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно добавлен"
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет пользователя из списка",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Удалить пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор удаляемого пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешн удален"
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с указанным идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет информацию о пользователе",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Обновить пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор обновляемого пользователя",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Имя",
                        "name": "Name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Фамилия",
                        "name": "Surname",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Возраст",
                        "name": "Age",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно обновлена"
                    },
                    "400": {
                        "description": "Неверное значение",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с таким идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/gateway/users/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает кол-во пользователей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователи"
                ],
                "summary": "Получить кол-во пользователей",
                "responses": {
                    "200": {
                        "description": "Кол-во элементов",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "401": {
                        "description": "Не авторизован",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "description": "Аутентифицирует пользователя",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Залогиниться",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Логин",
                        "name": "login",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "JWT-токен",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Создаёт нового пользователя без JWT. После регистрации получите токен через /login.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аутентификация"
                ],
                "summary": "Зарегистрировать пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя",
                        "name": "Name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Фамилия",
                        "name": "Surname",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Логин",
                        "name": "login",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Возраст",
                        "name": "Age",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Идентификатор созданного пользователя",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Не удалось создать пользователя",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "main.Program": {
            "type": "object",
            "properties": {
                "confirmedby": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "wasconfirmed": {
                    "type": "string"
                }
            }
        },
        "main.User": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "surname": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "Gateway",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
