apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  selector:
    pod: programs-service-pod # Трафик будет перенаправляться к подам с этой меткой.
  ports:
    - port: 8081 # Порт, куда будет перенаправляться трафик
      name: programs-api-port
    - port: 8010 # Порт GraphQL, как в compose
      name: programs-gql-port
  type: NodePort