package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"encoding/json"
	"fmt"
	"lab1/app"
	"lab1/graphq/graph/model"
	"lab1/models"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// DeleteAllPrograms is the resolver for the DeleteAllPrograms field.
func (r *mutationResolver) DeleteAllPrograms(ctx context.Context) (bool, error) {
	err := r.application.Database.DeleteAllPrograms()
	if err != nil {
		return false, gqlerror.Errorf("не удалось удалить элементы: %s", err.Error())
	}

	return true, nil
}

// DeleteProgram is the resolver for the deleteProgram field.
func (r *mutationResolver) DeleteProgram(ctx context.Context, id string) (bool, error) {
	r.application.Redis.Del(context.TODO(), id)
	err := r.application.Database.DeleteProgram(id)

	if err != nil {
		return false, gqlerror.Errorf("не удалось удалить элемент: %s", err.Error())
	}

	return true, nil
}

// AddProgram is the resolver for the addProgram field.
func (r *mutationResolver) AddProgram(ctx context.Context, val model.CreateProgramInput) (*model.Program, error) {
	if val.Price < 0 {
		return &model.Program{}, gqlerror.Errorf("неверные аргументы: Price: %d", val.Price)
	}

	confirmedUserId, err := bson.ObjectIDFromHex(val.Confirmuserid)
	if err != nil {
		return &model.Program{}, gqlerror.Errorf("некорректный id подтверждающего пользователя")
	}

	newProgram := models.Program{
		Name:         val.Name,
		Description:  val.Description,
		Price:        int(val.Price),
		WasConfirmed: "-",
		ConfirmedBy:  confirmedUserId,
	}
	insertedId, err := r.application.Database.AddProgram(&newProgram)
	if err != nil {
		return &model.Program{}, gqlerror.Errorf("не удалось записать в БД")
	}

	oid, ok := insertedId.InsertedID.(bson.ObjectID)
	if !ok {
		return &model.Program{}, gqlerror.Errorf("при добавлении новой программы сгенерированное id не типа ObjectID")
	}

	err = app.Write(r.application.Producer, oid.Hex(), confirmedUserId.Hex())
	if err != nil {
		return &model.Program{}, gqlerror.Errorf("ошибка при записи в очередь " + err.Error())
	}

	newProgramOutput := model.Program{
		Name:         newProgram.Name,
		Description:  newProgram.Description,
		Price:        int32(newProgram.Price),
		Wasconfirmed: "-",
		Confirmedby:  confirmedUserId.String(),
	}

	return &newProgramOutput, nil
}

// UpdateProgram is the resolver for the updateProgram field.
func (r *mutationResolver) UpdateProgram(ctx context.Context, val model.UpdateProgramInput) (bool, error) {
	new_name := val.Name
	new_description := val.Description
	new_price := val.Price

	var newValues bson.D

	if new_name != nil {
		newValues = append(newValues, bson.E{"name", *new_name})
	}
	if new_description != nil {
		newValues = append(newValues, bson.E{"description", *new_description})
	}
	if new_price != nil {
		new_price_int := *new_price
		if new_price_int < 0 {
			return false, gqlerror.Errorf("неверное значение price: %d", new_price_int)
		}
		newValues = append(newValues, bson.E{"price", new_price_int})
	}

	// Удаление из кеша.
	r.application.Redis.Del(context.TODO(), val.ID)

	// Обновление в БД.
	err := r.application.Database.UpdateProgram(val.ID, newValues)
	if err != nil {
		return false, gqlerror.Errorf("не удалось обновить запись: %s", err.Error())
	}

	return true, nil
}

// AllPrograms is the resolver for the allPrograms field.
func (r *queryResolver) AllPrograms(ctx context.Context) ([]*model.Program, error) {
	panic(fmt.Errorf("not implemented: AllPrograms - allPrograms"))
}

// Program is the resolver for the program field.
func (r *queryResolver) Program(ctx context.Context, id string) (*model.Program, error) {
	panic(fmt.Errorf("not implemented: Program - program"))
}

// ProgramsCount is the resolver for the programsCount field.
func (r *queryResolver) ProgramsCount(ctx context.Context) (int32, error) {
	panic(fmt.Errorf("not implemented: ProgramsCount - programsCount"))
}

// ProgramFilter is the resolver for the programFilter field.
func (r *queryResolver) ProgramFilter(ctx context.Context, filter model.ProgramFilterInput) ([]*model.Program, error) {
	programs, err := r.application.Database.FilterPrograms(filter)
	if err != nil {
		return nil, gqlerror.Errorf("не получить элементы по фильтру: %s", err.Error())
	}

	programsBytes, err := json.Marshal(programs)
	if err != nil {
		return nil, gqlerror.Errorf("не удалось сформировать ответ: %s", err.Error())
	}

	var results []*model.Program
	err = json.Unmarshal(programsBytes, &results)

	return results, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
