#go run github.com/99designs/gqlgen generate

type Program {
  _id: String!
  confirmedby: String!
  description: String!
  name: String!
  price: Int!
  wasconfirmed: String!
}

input CreateProgramInput {
  name: String!
  description: String!
  price: Int!
  confirmuserid: String!
}

input UpdateProgramInput {
  id: String!
  name: Int
  description: String
  price: Int
}

input ProgramFilterInput {
  confirmedby: String
  description: String
  name: String
  price: Int
  wasconfirmed: String
}

type Query {
  allPrograms: [Program!]!
  program(id: String!): Program!
  programsCount: Int!
  programFilter(filter: ProgramFilterInput!): [Program!]!
}

type Mutation {
  deleteAllPrograms: Boolean!
  deleteProgram(id: String!): Boolean!
  addProgram(val: CreateProgramInput!): Program!
  updateProgram(val: UpdateProgramInput!): Boolean!
}