// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/programs": {
            "get": {
                "description": "Возвращает список программ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Получить все программы тренировок",
                "responses": {
                    "200": {
                        "description": "Успешно получены все программы тренировок",
                        "schema": {
                            "$ref": "#/definitions/main.Program"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет все программы тренировок из списка",
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Удалить все программы тренировок",
                "responses": {
                    "200": {
                        "description": "Успешно удалены"
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/programs/": {
            "get": {
                "description": "Возвращает программу тренировок по индексу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Получить программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор программы",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно получена программа тренировок",
                        "schema": {
                            "$ref": "#/definitions/main.Program"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с указанным идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет в список тренировок новую программу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Добавить новую программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название программы",
                        "name": "Name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Описание программы",
                        "name": "Description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Стоимость программы",
                        "name": "Price",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Id подтверждающего пользователя",
                        "name": "ConfirmUserId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно добавлена"
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет программу тренировок из списка",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Удалить программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор удаляемой программы",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно удалена"
                    },
                    "400": {
                        "description": "Ошибки в передаваемых параметрах",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с указанным идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "405": {
                        "description": "Неверный метод",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Возвращает программу тренировок по индексу",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Обновить программу тренировок",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор обновляемой программы",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Название программы",
                        "name": "Name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Описание программы",
                        "name": "Description",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "Стоимость программы",
                        "name": "Price",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно обновлена"
                    },
                    "400": {
                        "description": "Неверное значение цены",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "404": {
                        "description": "Нет элемента с таким идентификатором",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        },
        "/programs/count": {
            "get": {
                "description": "Возвращает кол-во документов",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Программы тренировок"
                ],
                "summary": "Получить кол-во программ",
                "responses": {
                    "200": {
                        "description": "Кол-во элементов",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "422": {
                        "description": "Неподдерживаемые данные",
                        "schema": {
                            "$ref": "#/definitions/main.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "main.Program": {
            "type": "object",
            "properties": {
                "confirmedby": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "wasconfirmed": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "Симакин К.С. Акчурин А.Р.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
